version: '2.2'

services:
    voip:
        image: wt5_voip:latest
        container_name: Voip
        ports:
          - "5060:5060"
        networks:            
            dmz:
                ipv4_address : 192.168.1.5
        volumes:
          - ./VOIP/asterisk/extensions.conf:/etc/asterisk/extensions.conf
          - ./VOIP/asterisk/sip.conf:/etc/asterisk/sip.conf
          - ./VOIP/asterisk/loggers.conf:/etc/asterisk/logger.conf
          - ./VOIP/asterisk/users.conf:/etc/asterisk/users.conf
          - ./VOIP/asterisk/voicemail.conf:/etc/asterisk/voicemail.conf
        restart: always
networks:
    dmz:
       ipam:
         driver: default
         config:
              - subnet: 192.168.1.0/24
                gateway: 192.168.1.1
    
