version: '2'

services:
    resolv:
        build: 
            context: ./resolv
            dockerfile: Dockerfile
        networks:
            local:
                ipv4_address: 192.168.0.2
        volumes:
            - ./resolv/named.conf:/etc/bind/named.conf
        container_name: resolv
    soaint:
        build: 
            context: ./SOAint
            dockerfile: Dockerfile    
        networks:
            local:
                ipv4_address: 192.168.0.3
        volumes:
            - ./SOAint/named.conf:/etc/bind/named.conf
            - ./SOAint/local.wt2-5.ephec-ti.be:/etc/bind/local.wt2-5.ephec-ti.be
            - ./SOAint/0.168.192.in-addr-arpa:/etc/bind/0.168.192.in-addr-arpa
        container_name: soaint
    intranet:
        build:
            context: ./Intranet
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        networks:
            local:
                ipv4_address: 192.168.0.4
        volumes: 
            - ./Intranet/sites-available:/etc/apache2/sites-available
            - ./Intranet/index.php:/var/www/
        container_name: intranet
  
networks:
    local:
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
                  gateway:  192.168.0.1

    dmz: 
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway: 192.168.1.1
    
