version: '2'

services:
    resolv:
        build: 
            context: ./resolv
            dockerfile: Dockerfile
        networks:
            local:
                ipv4_address: 192.168.0.2
        volumes:
            - ./resolv/named.conf:/etc/bind/named.conf
        container_name: resolv

    soaint:
        build: 
            context: ./SOAint
            dockerfile: Dockerfile    
        networks:
            local:
                ipv4_address: 192.168.0.3
        volumes:
            - ./SOAint/named.conf:/etc/bind/named.conf
            - ./SOAint/local.wt2-5.ephec-ti.be:/etc/bind/local.wt2-5.ephec-ti.be
            - ./SOAint/0.168.192.in-addr-arpa:/etc/bind/0.168.192.in-addr-arpa
        container_name: soaint

    intranet:
        build:
            context: ./Intranet
            dockerfile: Dockerfile
        networks:
            local:
                ipv4_address: 192.168.0.4
        volumes: 
            - ./Intranet/intranet.conf:/etc/apache2/sites-available/intranet.conf
            - ./Intranet/index.php:/var/www/index.php
        container_name: intranet
  
    db:
        build: 
            context: ./DB
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        ports:  
            - "4200:4200"
        networks:
            local:
                ipv4_address: 192.168.0.5
        environment: 
            MYSQL_ROOT_PASSWORD: sqlpasswd
        container_name: db

networks:
    local:
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
                  gateway:  192.168.0.1
