version: '2'

services:   

    soaext:
        build: 
            context: ./SOAext
            dockerfile: Dockerfile
        networks:
            dmz:
                ipv4_address: 192.168.1.2
        volumes:
            - ./SOAext/named.conf:/etc/bind/named.conf
            - ./SOAext/wt1-5.ephec-ti.be:/etc/bind/wt1-5.ephec-ti.be
        container_name: soaext

    portail:
        build:
            context: ./Portail
            dockerfile: Dockerfile
        networks:
            dmz:
                ipv4_address: 192.168.1.4
        volumes:
            - ./Portail/sites-available/:/etc/apache2/sites-available/
            - ./Portail/index.html:/var/www/index.html
        container_name: portail

    b2b:
        build:
            context: ./B2B
            dockerfile: Dockerfile
        networks:
            dmz:
                ipv4_address: 192.168.1.3
        volumes: 
            - ./B2B/sites-available/:/etc/apache2/sites-available/
            - ./B2B/index.php:/var/www/index.php
        container_name: b2b

        
networks: 
    local:
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
                  gateway:  192.168.0.1

    dmz: 
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway:  192.168.1.1
    
