version: '2'

services:   

    soaext:
        build: 
            context: ./SOAext
            dockerfile: Dockerfile
        ports:
                - "53:53/tcp"
                - "53:53/udp"
        networks:
            dmz:
                ipv4_address: 192.168.1.2
        volumes:
            - ./SOAext/named.conf:/etc/bind/named.conf
            - ./SOAext/wt1-5.ephec-ti.be:/etc/bind/wt1-5.ephec-ti.be
        container_name: soaext

    sitesDMZ:
        build:
            context: ./Sites_DMZ
            dockerfile: Dockerfile
        ports:
                - "80:80"
                - "443:443"
        networks:
            dmz:
                ipv4_address: 192.168.1.3
        volumes: 
            - ./Sites_DMZ/sites-available/:/etc/apache2/sites-available/
            - ./Sites_DMZ/www/:/var/www/
        container_name: sitesdmz

        
networks:
    dmz: 
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway:  192.168.1.1
    
